version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 4 2 */4 *"
    assignees:
      - "Gustry"

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "cron"
      cronjob: "0 4 2 */4 *"
    assignees:
      - "Gustry"
