variables:
  FACTORY_PRODUCT_NAME: pyqgis-server
  FACTORY_PACKAGE_TYPE: application

stages:
- test
- build
- docker
- deploy
- release
- post_release

#-----------------
# Tests
#-----------------

.tests:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: test
  script:
    - source ~/.bashrc
    - make install install-tests
    - pip list -l
    - make test
  tags:
    - factory-plain
  variables:
    ASYNC_TEST_TIMEOUT: "20"

tests:
  extends: .tests
  resource_group: py_qgis_server_tests
  parallel:
    matrix:
    - QGIS_FLAVOR: ['3.44', '3.40', '3.34']

#---------------
# Build
#---------------

build:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: build
  script:
    - source ~/.bashrc
    - make dist deliver
  environment:
    name: snap
  tags:
    - factory-plain
  only:
    refs:
      - tags
      - master
  except:
      - schedules
      - triggers


# Docker build
include: '/docker/.gitlab-ci.yml'

