variables:
  FACTORY_PRODUCT_NAME: pyqgis-server
  FACTORY_PACKAGE_TYPE: application

stages:
- lint
- test
- build
- package
- docker
- deploy
- release
- post_release

#-----------------
# Lint
#-----------------

lint:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: lint
  script:
    - make install lint
  tags:
    - factory-plain
  variables:
    ASYNC_TEST_TIMEOUT: "20"
  parallel:
    matrix:
    - QGIS_FLAVOR: ["ltr"]


#-----------------
# Tests
#-----------------

.tests:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: test
  script:
    - make install test
  tags:
    - factory-plain
  variables:
    ASYNC_TEST_TIMEOUT: "20"

tests:
  extends: .tests
  resource_group: py_qgis_server_tests
  parallel:
    matrix:
    - QGIS_FLAVOR: ['3.44', '3.40', '3.34']

#---------------
# Build
#---------------

.release_rules:
  - if: '$CI_COMMIT_TAG =~ /^(?:release-|v)?\d+\.\d+\.\d+(?:-.*)?$/'
    variables:
      DIST_RELEASE: "true"

build:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  tags:
    - factory-plain
  stage: build
  rules:
    - if: $RELEASE_BRANCH == "true"
    - !reference [.release_rules]
  script:
    - make dist deliver
    - echo "WHEEL=`ls -1 dist/py_qgis_server-*.whl`" > build.env
    - cat build.env
  environment:
    name: snap
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - "dist/py_qgis_server-*.whl"
    expire_in: 1 week

# --------------
# Package
# --------------

package:
  image: ${REGISTRY_URL}/factory-ci-runner:fabric-ci
  tags:
    - fabric
  stage: package
  rules:
    - if: $RELEASE_BRANCH == "true"
    - !reference [.release_rules]
  dependencies:
    - build
  script:
    - upload_to_packages_server ${WHEEL} pub/whl/py-qgis-server/


# Docker build
include: '/docker/.gitlab-ci.yml'

