# Ruff configuration
# See https://docs.astral.sh/ruff/configuration/
line-length = 120
target-version = "py310"

[lint]
extend-select = ["E", "F", "I", "ANN", "W", "T", "COM", "RUF"]
ignore = ["ANN101", "ANN102", "ANN002", "ANN003"]

[format]
indent-style = "space"

[lint.per-file-ignores]
"tests/*" = ["T201"]
"pyqgisservercontrib/core/componentmanager.py" = ["ANN401"]

[lint.isort]
lines-between-types = 1
known-first-party = [
    "pyqgisserver",
    "pyqgisservercontrib", 
]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "qgis",
    "first-party",
    "local-folder",
]

[lint.isort.sections]
qgis = ["qgis"]

[lint.flake8-annotations]
ignore-fully-untyped = true
suppress-none-returning = true
suppress-dummy-args = true

