variables:
    QGIS_FLAVOR: release

#-------------
# Build
#-------------

build-docker:
  stage: docker
  script:
    - make -C docker build deliver pushrc clean FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  artifacts:
    paths:
      - "docker/factory.manifest"
  only:
    refs:
      - tags
      - 1.3.x
  tags:
    - infrav3

#-------------
# deploy
#-------------

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update -C MUTU map --annotate="Updated image ($CI_COMMIT_SHORT_SHA)"
  environment:
    name: snap
  only:
    refs:
       - tags
       - 1.3.x
  tags:
    - infrav3

#-------------
# Release
#-------------

-release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-map-server-$QGIS_FLAVOR
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: production
  when: manual
  only:
    refs:
      - tags
  tags:
    - infrav3
  variables:
    FACTORY_MANIFEST: "docker/factory.manifest"
  dependencies:
    - build-docker

