#-------------
# Build
#-------------

.build-docker:
  stage: docker
  script:
    - make version
    - make -C docker build deliver pushrc clean FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  artifacts:
    paths:
      - "docker/factory.manifest"
  only:
    refs:
      - tags
      - master
  tags:
    - infrav3-dind

build-docker:release:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: release

build-docker:ltr:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: ltr

build-docker:3.10:
  extends: .build-docker
  when: manual
  variables:
    QGIS_FLAVOR: "3.10"

#-------------
# deploy
#-------------

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update -C MUTU map --annotate="Updated image ($CI_COMMIT_SHORT_SHA)"
  environment:
    name: snap
  only:
    refs:
       - master
  tags:
    - infrav3-plain

#-------------
# Release
#-------------

.release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-map-server-$QGIS_FLAVOR
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: production
  when: manual
  only:
    refs:
      - tags
  tags:
    - infrav3-dind
  variables:
    FACTORY_MANIFEST: "docker/factory.manifest"

release:release:
  extends: .release
  variables:
    QGIS_FLAVOR: release
  dependencies:
    - build-docker:release

release:ltr:
  extends: .release
  variables:
    QGIS_FLAVOR: ltr
  dependencies:
    - build-docker:ltr

release:3.10:
  extends: .release
  variables:
    QGIS_FLAVOR: "3.10"
  dependencies:
    - build-docker:3.10

