#-------------
# Build
#-------------

.build-docker:
  stage: docker
  script:
    - make version
    - make -C docker build deliver pushrc clean FLAVOR=$QGIS_FLAVOR BUILD_TARGET=amqp
  environment:
    name: snap
  artifacts:
    paths:
      - "docker/factory-${QGIS_FLAVOR}.manifest"
  only:
    refs:
      - tags
      - master
  tags:
    - infrav3-dind


build-docker:release:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: release

build-docker:ltr:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: ltr

#
# Compatibility with previous ltr
#

build-docker:3.28:
  extends: .build-docker
  variables:
    QGIS_FLAVOR: "3.28"

#-------------
# deploy
#-------------

deploy_snap:
  image: ${REGISTRY_URL}/factory-ci-runner:package-management
  stage: deploy
  script:
    - update-service map
  environment:
    name: snap
  only:
    refs:
       - tags
       - master
  tags:
    - infrav3-plain

#-------------
# Release
#-------------

.release:
  image: ${REGISTRY_URL}/factory-ci-runner:package-management
  stage: release
  script:
    - release-image.sh qgis-map-server-$QGIS_FLAVOR
    - push-to-docker-hub.sh --clean
  environment:
    name: production
  when: manual
  # See https://about.gitlab.com/blog/2021/05/20/dag-manual-fix/#what-if-i-dont-want-this-new-behavior
  allow_failure: false
  only:
    refs:
      - tags
  tags:
    - infrav3-dind
  variables:
    FACTORY_MANIFEST: "docker/factory-${QGIS_FLAVOR}.manifest"

release:release:
  extends: .release
  variables:
    QGIS_FLAVOR: release
  dependencies:
    - build-docker:release

release:ltr:
  extends: .release
  variables:
    QGIS_FLAVOR: ltr
  dependencies:
    - build-docker:ltr

#
# Compatibility with previous ltr
#

release:3.28:
  extends: .release
  variables:
    QGIS_FLAVOR: "3.28"
  dependencies:
    - build-docker:3.28
