#!/bin/bash

set -e 

function help() {
    echo "Install lizmap plugin"
    echo "Usage:"
    echo "install-lizmap-plugin <installdir> [version]"
    echo ""
    exit 1
}

[[ $# -lt 1 ]] && help

INSTALL_DIR=$1

if [[ $# -gt 1 ]]; then
    LIZMAP_PLUGIN_VERSION=$2
else
    LIZMAP_PLUGIN_VERSION=$(_get_latest_release)
fi

_get_latest_release() {
    wget -q https://api.github.com/repos/3liz/lizmap-plugin/releases/latest -O - |\
        jq -r '.assets[0] | browser_download_url'

}

_install-plugin() {
    local plugindir=$INSTALL_DIR/lizmap
    if [ -d $plugindir ]; then
        local version=$(cat $plugindir/metadata.txt | grep "version=" |  cut -d '=' -f2)
        echo "Found installed version $version"
        if [ ! "$LIZMAP_PLUGIN_VERSION" = "$version" ]; then
            $remove_current=1
        else
            echo "Installed version match required version"
            return 0
        fi
    fi
    echo "Installing version $LIZMAP_PLUGIN_VERSION"
    wget https://github.com/3liz/lizmap-plugin/releases/download/$LIZMAP_PLUGIN_VERSION/lizmap.$LIZMAP_PLUGIN_VERSION.zip \
        -O lizmap-plugin.zip
    unzip -qq lizmap-plugin.zip -d lizmap-plugin-$LIZMAP_PLUGIN_VERSION
    (
        cd lizmap-plugin-$LIZMAP_PLUGIN_VERSION
        local files="lizmap/__init__.py lizmap/server lizmap/tooltip.py lizmap/metadata.txt"
        if [ "$remove_current" = "1" ]; then
            echo "Removing installed version"
            rm -rf $plugindir
        fi
        mkdir $plugindir
        cp -rLp $files $plugindir/
    )
    # Clean up stuff
    rm -rf lizmap-plugin.zip lizmap-plugin-$LIZMAP_PLUGIN_VERSION
}


_install-plugin

