name: 📖 Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'
      - '.github/workflows/publish-doc.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'

    - name: Set up NodeJS (for search index prebuilding)
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '18'

    - name: Cache project dependencies (pip)
      uses: actions/cache@v4.2.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('doc/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r doc/requirements.txt

    - name: Build HTML
      run: |
        make -C doc html

    - name: Bypass underscore
      run: touch doc/build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        branch: gh-pages
        folder: doc/build/html
        token: ${{ secrets.BOT_HUB_TOKEN }}
        git-config-name: ${{ secrets.BOT_NAME }}
        git-config-email: ${{ secrets.BOT_MAIL }}
