name: 🚀 Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "🚀 Release"
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

    - name: Set env
      # CI_COMMIT_TAG is used in Makefile
      run: echo "CI_COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Setup
      run: |
        make version

    - name: Install Python requirements
      run: pip install qgis-plugin-ci

    - name : Get current changelog
      run: qgis-plugin-ci changelog ${{ env.CI_COMMIT_TAG }} >> release.md

    - name: Build package
      run: |
        python setup.py sdist

    - name: Create release on GitHub
      uses: ncipollo/release-action@v1.8.6
      with:
        bodyFile: release.md
        token: ${{ secrets.BOT_HUB_TOKEN }}
        allowUpdates: true
        artifacts: "dist/*.tar.gz"

    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Tweet
      uses: mugi111/tweet-trigger-release@v1.2
      with:
        consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        tweet_body: "New version of Py-QGIS-Server ${{ env.RELEASE_VERSION }} for #QGIS https://github.com/3liz/py-qgis-server/releases"
