name: 🚀 Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "🚀 Release"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

    - name: Set env
      # CI_COMMIT_TAG is used in Makefile to not have the "RC" flag
      run: echo "CI_COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Get source code
      uses: actions/checkout@v4

    - name: Changelog
      id: changelog
      uses: 3liz/changelog-release@0.3.0

    - name: Set up Python 3.13
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.13'

#    - name: Check tag
#      run: tests/check_tag.sh ${{ env.CI_COMMIT_TAG }}

    - name: Setup
      run: |
        make manifest

    - name: Install Python requirements
      run: pip3 install --upgrade setuptools qgis-plugin-ci build

    - name : Get current changelog
      run: qgis-plugin-ci changelog ${{ env.CI_COMMIT_TAG }} >> release.md

    - name: Build package
      run: |
        make dist

    - name: Create release on GitHub
      uses: ncipollo/release-action@v1.16.0
      with:
        body: ${{ steps.changelog.outputs.markdown }}
        token: ${{ secrets.BOT_HUB_TOKEN }}
        allowUpdates: true
        artifacts: "dist/*.tar.gz"

    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
